# Generated by Django 5.0.1 on 2024-01-28 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuiaCompetencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=20)),
                ('specialty', models.CharField(max_length=20, null=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GuiaSpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Guia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, null=True)),
                ('description', models.TextField(null=True)),
                ('identifier_type', models.CharField(max_length=200, null=True)),
                ('identifier_character', models.CharField(max_length=200, null=True)),
                ('identifier_specialty', models.CharField(max_length=200, null=True)),
                ('identifier_subject', models.CharField(max_length=200, null=True)),
                ('identifier_course', models.CharField(max_length=200, null=True)),
                ('identifier_semester', models.CharField(max_length=2, null=True)),
                ('identifier_credits', models.IntegerField(default=0)),
                ('identifier_hours_total', models.IntegerField(default=0)),
                ('identifier_hours_presence', models.IntegerField(default=0, null=True)),
                ('identifier_department', models.CharField(max_length=200, null=True)),
                ('identifier_prelation', models.TextField(blank=True, null=True)),
                ('identifier_language', models.CharField(max_length=200, null=True)),
                ('coordinator', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GuiaChronogram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_entity', models.IntegerField()),
                ('block', models.IntegerField()),
                ('theme', models.IntegerField()),
                ('exercise', models.IntegerField()),
                ('guia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guias.guia')),
            ],
        ),
    ]
