# Generated by Django 5.0.1 on 2024-01-28 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuiaResultados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('priority', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='guia',
            name='competencies',
            field=models.ManyToManyField(to='guias.guiacompetencias'),
        ),
        migrations.AddField(
            model_name='guia',
            name='eval_criteria_others',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='guia',
            name='eval_criteria_practical',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='guia',
            name='eval_criteria_theory',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='guia',
            name='eval_instruments_others',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='guia',
            name='eval_instruments_practical',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='guia',
            name='eval_instruments_theory',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='guia',
            name='hours_activities',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='guia',
            name='hours_preparatioin',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='guia',
            name='hours_probes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='guia',
            name='hours_selfwork',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='guia',
            name='methodology_others',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='guia',
            name='methodology_practical',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='guia',
            name='methodology_theory',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='guia',
            name='teachers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='guia',
            name='coordinator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='coordinator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='guia',
            name='identifier_specialty',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='guias.guiaspecialty'),
        ),
        migrations.CreateModel(
            name='GuiaChronogramBlocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_entity', models.IntegerField()),
                ('block', models.IntegerField()),
                ('theme', models.IntegerField()),
                ('exercise', models.IntegerField()),
                ('chronogram', models.IntegerField(default=0)),
                ('guia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guias.guia')),
            ],
        ),
        migrations.CreateModel(
            name='GuiaContents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('priority', models.IntegerField(default=1)),
                ('parent', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='guias.guiacontents')),
            ],
        ),
        migrations.AddField(
            model_name='guia',
            name='contents',
            field=models.ManyToManyField(to='guias.guiacontents'),
        ),
        migrations.AddField(
            model_name='guia',
            name='results',
            field=models.ManyToManyField(to='guias.guiaresultados'),
        ),
        migrations.DeleteModel(
            name='GuiaChronogram',
        ),
    ]
