# Generated by Django 5.0.1 on 2024-01-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guias', '0002_guiaresultados_guia_competencies_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuiaResources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
                ('author', models.CharField(max_length=200, null=True)),
                ('editorial', models.CharField(max_length=200, null=True)),
                ('href', models.CharField(max_length=200, null=True)),
                ('type', models.CharField(default='a', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='guiachronogramblocks',
            name='guia',
        ),
        migrations.AddField(
            model_name='guia',
            name='calification_continual_evaluation_attitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='guia',
            name='calification_continual_evaluation_practical',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='guia',
            name='calification_continual_evaluation_theory',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='guia',
            name='calification_disabled_attitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='guia',
            name='calification_disabled_practical',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='guia',
            name='calification_disabled_theory',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='guia',
            name='calification_extraordinary',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='guia',
            name='calification_ordinary',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='guia',
            name='chronogram',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='guia',
            name='resources',
            field=models.ManyToManyField(to='guias.guiaresources'),
        ),
    ]
