# Generated by Django 5.0.1 on 2024-01-28 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guias', '0004_alter_guia_eval_criteria_others_alter_guia_resources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guia',
            name='contents',
            field=models.ManyToManyField(default=0, to='guias.guiacontents'),
        ),
        migrations.AlterField(
            model_name='guia',
            name='identifier_specialty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='guias.guiaspecialty'),
        ),
        migrations.AlterField(
            model_name='guia',
            name='resources',
            field=models.ManyToManyField(default=0, to='guias.guiaresources'),
        ),
        migrations.AlterField(
            model_name='guia',
            name='results',
            field=models.ManyToManyField(default=0, to='guias.guiaresultados'),
        ),
    ]
