# Generated by Django 5.0.1 on 2024-01-28 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guias', '0005_alter_guia_contents_alter_guia_identifier_specialty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guia',
            name='identifier_specialty',
            field=models.ForeignKey(default='hola', null=True, on_delete=django.db.models.deletion.CASCADE, to='guias.guiaspecialty'),
        ),
    ]
