# Generated by Django 5.0.1 on 2024-01-28 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guias', '0006_alter_guia_identifier_specialty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guia',
            name='identifier_specialty',
            field=models.ForeignKey(choices=[('a', 'a'), ('b', 'b')], default='hola', null=True, on_delete=django.db.models.deletion.CASCADE, to='guias.guiaspecialty'),
        ),
    ]
