# Generated by Django 5.0.1 on 2024-01-28 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guias', '0007_alter_guia_identifier_specialty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guia',
            name='contents',
            field=models.ManyToManyField(to='guias.guiacontents'),
        ),
        migrations.AlterField(
            model_name='guia',
            name='identifier_specialty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='guias.guiaspecialty'),
        ),
        migrations.AlterField(
            model_name='guia',
            name='results',
            field=models.ManyToManyField(to='guias.guiaresultados'),
        ),
    ]
