# Generated by Django 5.0.1 on 2024-01-28 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guias', '0009_alter_guiacontents_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guia',
            name='contents',
        ),
        migrations.RemoveField(
            model_name='guia',
            name='resources',
        ),
        migrations.RemoveField(
            model_name='guia',
            name='results',
        ),
    ]
