# Generated by Django 5.0.1 on 2024-01-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guias', '0011_guia_contents_guia_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='guia',
            name='resources',
            field=models.ManyToManyField(default=0, to='guias.guiaresources'),
        ),
    ]
