# Generated by Django 5.0.1 on 2024-01-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guias', '0013_alter_guia_coordinator'),
    ]

    operations = [
        migrations.AddField(
            model_name='guiachronogramblocks',
            name='competencies',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='guiachronogramblocks',
            name='exam',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='guiachronogramblocks',
            name='exercise_content',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='guiachronogramblocks',
            name='special_activity',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='guiachronogramblocks',
            name='exercise',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
