# Generated by Django 5.0.1 on 2024-01-31 11:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guias', '0014_guiachronogramblocks_competencies_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuiaChronogram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='GuiaCompetencias',
            new_name='GuiaCompetencies',
        ),
        migrations.RenameModel(
            old_name='GuiaResultados',
            new_name='GuiaResults',
        ),
        migrations.AddField(
            model_name='guia',
            name='course_code',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='guia',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guia',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='guiachronogramblocks',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guiachronogramblocks',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='guia',
            name='coordinator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coordinator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='guia',
            name='chronogram',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='guias.guiachronogram'),
        ),
        migrations.AlterField(
            model_name='guiachronogramblocks',
            name='chronogram',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guias.guiachronogram'),
        ),
    ]
